import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmCompilerOptions
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework
import org.gradle.api.publish.maven.MavenPublication
import org.gradle.api.publish.maven.tasks.PublishToMavenLocal
import java.util.Base64
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.kotlinSerialization)
    id("org.jetbrains.kotlin.plugin.compose") version libs.versions.kotlin.get()
    id("org.jetbrains.compose") version "1.10.0"
    `maven-publish`
}

// Repo-specific groupId avoids GitHub Packages 422 after repo transfer (package was under previous owner).
val githubRepo = System.getenv("GITHUB_REPOSITORY") ?: "PrathameshAdate05/air-canada-chat-library"
group = "io.github." + githubRepo.lowercase().replace("/", ".").replace("-", "_")
version = project.findProperty("LIB_VERSION")?.toString() ?: "1.0.0"

// ---------- COMPOSE RESOURCES (public Res so UI can reference drawables) ----------
compose.resources {
    publicResClass = true
}

// ---------- CONNECT CONFIG (from local.properties, overwrites stub) ----------
val generateConnectConfig = tasks.register("generateConnectConfig") {
    val outputFile = file("src/commonMain/kotlin/com/example/chat_poc/config/LibraryConnectConfig.kt")
    val localPropsFile = rootProject.file("local.properties")
    outputs.file(outputFile)
    if (localPropsFile.exists()) inputs.file(localPropsFile)
    doLast {
        val props = Properties()
        if (localPropsFile.exists()) localPropsFile.reader().use { props.load(it) }
        val apiGateway = (props.getProperty("API_GATEWAY") ?: "").replace("\\", "\\\\").replace("\"", "\\\"")
        val contactFlowId = (props.getProperty("CONTACT_FLOW_ID") ?: "").replace("\\", "\\\\").replace("\"", "\\\"")
        val instanceId = (props.getProperty("INSTANCE_ID") ?: "").replace("\\", "\\\\").replace("\"", "\\\"")
        val region = (props.getProperty("REGION") ?: "").replace("\\", "\\\\").replace("\"", "\\\"")
        val hasAll = apiGateway.isNotBlank() && contactFlowId.isNotBlank() && instanceId.isNotBlank() && region.isNotBlank()
        outputFile.parentFile.mkdirs()
        outputFile.writeText("""
package com.example.chat_poc.config

/**
 * Connect config baked in at library build time from local.properties.
 * Do not edit; generated by Gradle task generateConnectConfig.
 */
object LibraryConnectConfig {
    fun get(): ConnectConfig? = if (hasConfig) ConnectConfig(
        apiGatewayUrl = "$apiGateway",
        contactFlowId = "$contactFlowId",
        instanceId = "$instanceId",
        region = "$region"
    ) else null

    private const val hasConfig = $hasAll
}
""".trimIndent())
    }
}

// ---------- AI AGENT AVATAR: embed as Base64 so it loads without assets/R (reliable in library AAR) ----------
val aiAvatarSource = file("src/commonMain/composeResources/drawable/ai_agent_avatar.png")
val generateAiAvatarBase64 = tasks.register("generateAiAvatarBase64") {
    notCompatibleWithConfigurationCache("Task uses project.file() and script references for Base64 embedding")
    inputs.file(aiAvatarSource)
    val outDir = project.file("build/generated/ai_avatar_base64")
    outputs.dir(outDir)
    onlyIf { aiAvatarSource.exists() }
    doLast {
        val dir = outDir
        val outputFile = File(dir, "com/example/chat_poc/ui/AiAvatarData.kt")
        val bytes = aiAvatarSource.readBytes()
        val base64 = Base64.getEncoder().encodeToString(bytes)
        outputFile.parentFile.mkdirs()
        outputFile.writeText("""
package com.example.chat_poc.ui

/** Generated by Gradle task generateAiAvatarBase64. Do not edit. */
internal object AiAvatarData {
    const val BASE64: String = "$base64"
}
""".trimIndent())
    }
}
// ---------- HEADER LOGO (AC logo): Base64 embedding for library AAR ----------
val headerLogoSource = file("src/commonMain/composeResources/drawable/ac_logo.png")
val generateHeaderLogoBase64 = tasks.register("generateHeaderLogoBase64") {
    notCompatibleWithConfigurationCache("Task uses project.file() and script references for Base64 embedding")
    inputs.file(headerLogoSource)
    val outDir = project.file("build/generated/header_logo_base64")
    outputs.dir(outDir)
    onlyIf { headerLogoSource.exists() }
    doLast {
        val dir = outDir
        val outputFile = File(dir, "com/example/chat_poc/ui/HeaderLogoData.kt")
        val bytes = headerLogoSource.readBytes()
        val base64 = Base64.getEncoder().encodeToString(bytes)
        outputFile.parentFile.mkdirs()
        outputFile.writeText("""
package com.example.chat_poc.ui

/** Generated by Gradle task generateHeaderLogoBase64. Do not edit. */
internal object HeaderLogoData {
    const val BASE64: String = "$base64"
}
""".trimIndent())
    }
}
// ---------- CUSTOMER AVATAR: same Base64 embedding for library AAR ----------
val customerAvatarSource = file("src/commonMain/composeResources/drawable/customer_avatar.png")
val generateCustomerAvatarBase64 = tasks.register("generateCustomerAvatarBase64") {
    notCompatibleWithConfigurationCache("Task uses project.file() and script references for Base64 embedding")
    inputs.file(customerAvatarSource)
    val outDir = project.file("build/generated/customer_avatar_base64")
    outputs.dir(outDir)
    onlyIf { customerAvatarSource.exists() }
    doLast {
        val dir = outDir
        val outputFile = File(dir, "com/example/chat_poc/ui/CustomerAvatarData.kt")
        val bytes = customerAvatarSource.readBytes()
        val base64 = Base64.getEncoder().encodeToString(bytes)
        outputFile.parentFile.mkdirs()
        outputFile.writeText("""
package com.example.chat_poc.ui

/** Generated by Gradle task generateCustomerAvatarBase64. Do not edit. */
internal object CustomerAvatarData {
    const val BASE64: String = "$base64"
}
""".trimIndent())
    }
}

// Any task that compiles Kotlin (including Android-KMP compileAndroidMain) or builds source jars must run after generateConnectConfig
tasks.matching {
    it.name.contains("compile") && (it.name.contains("Kotlin") || it.name == "compileAndroidMain")
}.configureEach {
    dependsOn(generateConnectConfig)
    if (name.contains("Android")) {
        dependsOn(generateAiAvatarBase64)
        dependsOn(generateCustomerAvatarBase64)
        dependsOn(generateHeaderLogoBase64)
    }
    // iOS also uses Base64-embedded images (same as Android) so generated *Data.kt must exist
    if (name.contains("Ios") || name.contains("ios")) {
        dependsOn(generateAiAvatarBase64)
        dependsOn(generateCustomerAvatarBase64)
        dependsOn(generateHeaderLogoBase64)
    }
}
tasks.matching { it.name.endsWith("SourcesJar") || it.name == "sourcesJar" }.configureEach {
    dependsOn(generateConnectConfig)
    dependsOn(generateAiAvatarBase64, generateCustomerAvatarBase64, generateHeaderLogoBase64)
}
tasks.matching { it.name == "androidSourcesJar" }.configureEach {
    dependsOn(generateAiAvatarBase64)
    dependsOn(generateCustomerAvatarBase64)
    dependsOn(generateHeaderLogoBase64)
}

kotlin {

    // ---------- ANDROID (Android-KMP library plugin) ----------
    androidLibrary {
        namespace = "com.example.chat_poc"
        compileSdk = 35
        minSdk = 24
        compilations.configureEach {
            compileTaskProvider.configure {
                compilerOptions {
                    (this as KotlinJvmCompilerOptions).jvmTarget.set(JvmTarget.JVM_1_8)
                    freeCompilerArgs.add("-Xexpect-actual-classes")
                }
            }
        }
    }

    // ---------- iOS XCFRAMEWORK ----------
    val xcf = XCFramework()

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { target ->
        target.compilations.all {
            compileTaskProvider.configure {
                compilerOptions.freeCompilerArgs.add("-Xexpect-actual-classes")
            }
        }
        target.binaries.framework {
            baseName = "ChatSDK"
            isStatic = false
            freeCompilerArgs += "-Xobjc-generics"
            xcf.add(this)
        }
    }

    // ---------- SOURCE SETS ----------
    // Create iosMain so shared code in src/iosMain/ is used by all iOS targets (iosArm64, iosSimulatorArm64, iosX64).
    // Without this, only iosArm64Main, iosSimulatorArm64Main, iosX64Main exist and "iosMain" is not found.
    sourceSets {
        val iosMain by creating {
            dependsOn(getByName("commonMain"))
        }
        getByName("iosArm64Main").dependsOn(iosMain)
        getByName("iosSimulatorArm64Main").dependsOn(iosMain)
        getByName("iosX64Main").dependsOn(iosMain)

        getByName("androidMain").kotlin.srcDir("build/generated/ai_avatar_base64")
        getByName("androidMain").kotlin.srcDir("build/generated/customer_avatar_base64")
        getByName("androidMain").kotlin.srcDir("build/generated/header_logo_base64")
        // iOS uses the same Base64-embedded image data as Android (Compose Res.drawable not visible to Native)
        iosMain.kotlin.srcDir("build/generated/ai_avatar_base64")
        iosMain.kotlin.srcDir("build/generated/customer_avatar_base64")
        iosMain.kotlin.srcDir("build/generated/header_logo_base64")
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.ui)
            implementation(compose.material3)
            implementation("org.jetbrains.compose.material:material-icons-extended:1.7.3")
            implementation(compose.components.resources)

            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)

            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.websockets)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
        }

        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
            implementation(libs.androidx.activity.compose.v1122)
            implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.6")
            // Markwon: native Android markdown (TextView-based, tables supported)
            implementation("io.noties.markwon:core:4.6.2")
            implementation("io.noties.markwon:ext-tables:4.6.2")
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
            // Full markdown rendering (tables, italics, horizontal rules) to match Android
            implementation("com.mikepenz:multiplatform-markdown-renderer:0.39.2")
            implementation("com.mikepenz:multiplatform-markdown-renderer-m3:0.39.2")
        }
        // Skiko: one artifact per target (iosMain is shared, so adding all three there would require
        // every target to resolve all three and fail variant matching). Add only the matching one per target.
        getByName("iosArm64Main").dependencies {
            implementation("org.jetbrains.skiko:skiko-iosarm64:0.8.18")
        }
        getByName("iosSimulatorArm64Main").dependencies {
            implementation("org.jetbrains.skiko:skiko-iossimulatorarm64:0.8.18")
        }
        getByName("iosX64Main").dependencies {
            implementation("org.jetbrains.skiko:skiko-iosx64:0.8.18")
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

// ---------- PUBLISHING (GitHub only: Maven Local + GitHub Packages) ----------
// KMP creates root (shared) + target publications automatically.
// With Android-KMP plugin, the single Android variant is included in the root publication by default.
// Task: publishAndroidPublicationToGitHubPackagesRepository (or publishAllPublicationsToGitHubPackagesRepository).
// Repo-specific artifactId (lowercase) avoids 422 when package was created under previous owner.
publishing {
    repositories {
        mavenLocal()

        maven {
            name = "GitHubPackages"
            val repo = System.getenv("GITHUB_REPOSITORY") ?: "PrathameshAdate05/air-canada-chat-library"
            url = uri("https://maven.pkg.github.com/$repo")
            credentials {
                username = System.getenv("GITHUB_ACTOR") ?: ""
                password = System.getenv("GITHUB_TOKEN") ?: ""
            }
        }
    }
    publications.withType<MavenPublication>().configureEach {
        if (name == "android") artifactId = "chat-library-poc-android"
    }
}
